# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: cffcaff388f491d1bfe4835b89675f4b0c4fa4a29747e982bbefc156267b5844bf487ca50d7489a532a59409bd4ad7a569fd3ddf112a84f0fc1c4556fe8901a0

test:
  secret_key_base: 5852f619e11969a407d28be45096ef76fcc1a3e78cf9726c1f70125e16774fd8991025c59a70f4da2e3d186ff263d968098b70e647317e9605eec0ff1cf7f8d7

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
